name: vec2vec
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - toml
  - pip:
      - accelerate
      - sentence-transformers
      - transformers
      - diffusers
      - nltk
      - evaluate
      - beir
      - vec2text
      - wandb
      - safetensors
      - huggingface_hub
      - datasets
      - torchmetrics
      - einops
      - peft
